"""initialized

Revision ID: 8af2a1213a61
Revises: 
Create Date: 2026-05-19 14:28:30.929284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '8af2a1213a61'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipments',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipments_name'), 'equipments', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('setting_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_setting_key'), 'system_settings', ['setting_key'], unique=True)
    op.create_table('zones',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_name'), 'zones', ['name'], unique=True)
    op.create_table('cameras',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('rtsp_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cameras_name'), 'cameras', ['name'], unique=False)
    op.create_index(op.f('ix_cameras_zone_id'), 'cameras', ['zone_id'], unique=False)
    op.create_table('users',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('zone_equipment_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zone_equipment_rules_equipment_id'), 'zone_equipment_rules', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_zone_equipment_rules_zone_id'), 'zone_equipment_rules', ['zone_id'], unique=False)
    op.create_table('ai_events',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('image_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_events_camera_id'), 'ai_events', ['camera_id'], unique=False)
    op.create_index(op.f('ix_ai_events_event_type'), 'ai_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_ai_events_user_id'), 'ai_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_ai_events_zone_id'), 'ai_events', ['zone_id'], unique=False)
    op.create_table('camera_ai_configs',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('enable_ppe', sa.Boolean(), nullable=False),
    sa.Column('enable_face_recognition', sa.Boolean(), nullable=False),
    sa.Column('enable_idle_detection', sa.Boolean(), nullable=False),
    sa.Column('enable_zone_detection', sa.Boolean(), nullable=False),
    sa.Column('frame_skip', sa.Integer(), nullable=False),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_ai_configs_camera_id'), 'camera_ai_configs', ['camera_id'], unique=True)
    op.create_table('dashboard_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=False),
    sa.Column('logout_time', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_sessions_user_id'), 'dashboard_sessions', ['user_id'], unique=False)
    op.create_table('user_zone_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_zone_permissions_user_id'), 'user_zone_permissions', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_zone_permissions_zone_id'), 'user_zone_permissions', ['zone_id'], unique=False)
    op.create_table('worker_images',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('face_embedding', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_images_user_id'), 'worker_images', ['user_id'], unique=False)
    op.create_table('alerts',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['ai_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_event_id'), 'alerts', ['event_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_table('face_recognition_events',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('matched_user_id', sa.Integer(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('is_authorized', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['ai_events.id'], ),
    sa.ForeignKeyConstraint(['matched_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_recognition_events_event_id'), 'face_recognition_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_face_recognition_events_matched_user_id'), 'face_recognition_events', ['matched_user_id'], unique=False)
    op.create_table('idle_events',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('idle_seconds', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['ai_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idle_events_event_id'), 'idle_events', ['event_id'], unique=False)
    op.create_table('ppe_events',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['ai_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ppe_events_equipment_id'), 'ppe_events', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_ppe_events_event_id'), 'ppe_events', ['event_id'], unique=False)
    op.create_table('zone_violation_events',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('violation_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_authorized', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['ai_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zone_violation_events_event_id'), 'zone_violation_events', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zone_violation_events_event_id'), table_name='zone_violation_events')
    op.drop_table('zone_violation_events')
    op.drop_index(op.f('ix_ppe_events_event_id'), table_name='ppe_events')
    op.drop_index(op.f('ix_ppe_events_equipment_id'), table_name='ppe_events')
    op.drop_table('ppe_events')
    op.drop_index(op.f('ix_idle_events_event_id'), table_name='idle_events')
    op.drop_table('idle_events')
    op.drop_index(op.f('ix_face_recognition_events_matched_user_id'), table_name='face_recognition_events')
    op.drop_index(op.f('ix_face_recognition_events_event_id'), table_name='face_recognition_events')
    op.drop_table('face_recognition_events')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_event_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_worker_images_user_id'), table_name='worker_images')
    op.drop_table('worker_images')
    op.drop_index(op.f('ix_user_zone_permissions_zone_id'), table_name='user_zone_permissions')
    op.drop_index(op.f('ix_user_zone_permissions_user_id'), table_name='user_zone_permissions')
    op.drop_table('user_zone_permissions')
    op.drop_index(op.f('ix_dashboard_sessions_user_id'), table_name='dashboard_sessions')
    op.drop_table('dashboard_sessions')
    op.drop_index(op.f('ix_camera_ai_configs_camera_id'), table_name='camera_ai_configs')
    op.drop_table('camera_ai_configs')
    op.drop_index(op.f('ix_ai_events_zone_id'), table_name='ai_events')
    op.drop_index(op.f('ix_ai_events_user_id'), table_name='ai_events')
    op.drop_index(op.f('ix_ai_events_event_type'), table_name='ai_events')
    op.drop_index(op.f('ix_ai_events_camera_id'), table_name='ai_events')
    op.drop_table('ai_events')
    op.drop_index(op.f('ix_zone_equipment_rules_zone_id'), table_name='zone_equipment_rules')
    op.drop_index(op.f('ix_zone_equipment_rules_equipment_id'), table_name='zone_equipment_rules')
    op.drop_table('zone_equipment_rules')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_cameras_zone_id'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_name'), table_name='cameras')
    op.drop_table('cameras')
    op.drop_index(op.f('ix_zones_name'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_system_settings_setting_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_equipments_name'), table_name='equipments')
    op.drop_table('equipments')
    # ### end Alembic commands ###
