"""modified user model

Revision ID: cdb266386f9f
Revises: 9dd83d090bea
Create Date: 2026-05-26 14:13:26.130633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'cdb266386f9f'
down_revision: Union[str, Sequence[str], None] = '9dd83d090bea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column(
        'users',
        sa.Column(
        'is_trained',
        sa.Boolean(),
        nullable=False,
        server_default=sa.text('false')
    )
)    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_trained')
    op.drop_column('users', 'profile_image')
    # ### end Alembic commands ###
